name: Dev Flow
on: 
    push:
        branches-ignore:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        name: Test building with Webpack
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci 
            - run: npm run build:prod 